config/routes.rb
Rails.application.routes.draw do

  resources :dogs

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/dog.rb
class Dog < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/dogs_controller.rb
class DogsController < ApplicationController
  before_action :current_dog, only: [:show, :edit, :update, :destroy]

  def index
    @dogs = Dog.all
  end

  def show

  end

  def new
    @dog = Dog.new
  end

  def create
    @dog = Dog.create(dog_params)

    redirect_to dog_path(@dog)
  end

  def edit
    @dog = Dog.find(params[:id])
  end

  def update
    @dog = Dog.find(params[:id])
    @dog.update(dog_params)

    redirect_to dog_path(@dog)
  end

  def destroy
    @dog.destroy

    redirect_to dogs_path
  end

  private

  def dog_params
    params.require(:dog).permit(:name, :motto)
  end

  def current_dog
    @dog = Dog.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dogs_helper.rb
module DogsHelper
end

app/views/dogs/edit.html.erb
<h3>Actualizar información</h3>
<%= form_with model: @dog do |form| %>
  <%= form.text_field :name, placeholder: "name" %>
  <%= form.text_field :motto, placeholder: "motto" %>

  <%= form.submit %>
<% end %>

app/views/dogs/index.html.erb
<h1>Mis perros</h1>

<table>
  <tr>
    <thead>
        <th>Nombre</th>
        <th>Descripcion</th>
    </thead>
  </tr>
  <% @dogs.each do |dog| %>
  <tr>
    <td><%= dog.name %></td>
    <td><%= dog.motto %></td>
    <td>
      <%= button_to 'Mostrar', dog_path(dog), method: 'get'%>
    </td>
    <td>
    <%= button_to 'Editar', edit_dog_path(dog), method: 'get'%>
    </td>
    <td>
      <%= button_to 'Eliminar', dog_path(dog), method: 'delete', data: { confirm: 'Are you sure?' } %>
    </td>

  </tr>
    <% end %>
</table>
<%= button_to "Añadir perro", new_dog_path ,method: 'get'%>

app/views/dogs/new.html.erb
<h3>Crea un perro</h3>
<%= form_with model: @dog do |form| %>
  <%= form.text_field :name, placeholder: "name" %>
  <%= form.text_field :motto, placeholder: "motto" %>

  <%= form.submit %>
<% end %>

<!-- <%= form_for @dog do |form| %>
  <%= form.text_field :name, placeholder: 'name' %>
  <%= form.text_field :motto, placeholder: 'motto' %>
  <%= form.submit %>
<% end %> -->

app/views/dogs/show.html.erb
<h1><%= @dog.name %></h1>
<h4>"<%= @dog.motto %>"</h4>

<%= link_to "Volver", dogs_path %>